### ISSUE TITLE
Compile to es5

### ISSUE THREAD

**Issue by SpainTrain** [exelban/react-swipe-component#1]
It appears that as of v1.1.0, this package is exporting a source file using es2015 features.  

- This should have been a major bump
- This makes it not possible to use this package in any but the most recent browsers

Would you accept a PR that compiles this down to es5?

**Comment by exelban** [comment]
@SpainTrain of course you can make PR. I will accept changes.

**Comment by exelban** [comment]
@SpainTrain also i find some problems and publish v1.1.1 a few hour ago.

**Comment by SpainTrain** [comment]
yup, I saw the update but our build still failed with that version due to es2015 features :+1:

**Comment by exelban** [comment]
@SpainTrain can you send me log with errors?
And what you used to compile?

**Comment by SpainTrain** [comment]
webpack

```
ERROR in vendor.c4c48af58b7c0c5037ad.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/react-swipe-component/lib/Swipe.js:22,0][vendor.c4c48af58b7c0c5037ad.js:109652,19]

ERROR in vendor.c4c48af58b7c0c5037ad.js from UglifyJs
Unexpected token punc «(», expected punc «:» [./~/react-swipe-component/lib/Swipe.js:22,0][vendor.c4c48af58b7c0c5037ad.js:109652,19]
```
