### ISSUE TITLE
Swipe disables buttons?

### ISSUE THREAD

**Issue by gbishop** [exelban/react-swipe-component#9]
In Chrome on my Android phone, buttons don't work on pages wrapped with Swipe. You can see my code [here](https://github.com/gbishop/tar-heel-reader-17/blob/master/src/NavFrame.tsx#L44-L67)

Am I doing something incorrectly? The buttons work on my Chromebook.

Thanks
gb

**Comment by gbishop** [comment]
Ah, I see if I set preventDefaultEvent to false they work.

**Comment by exelban** [comment]
@gbishop, preventDefaultEvent fix the problem?

**Comment by gbishop** [comment]
Yes. It might be helpful to other to change 

> Sometimes you would like the target to scroll natively.
to
> You may want to set this to false to enable native scrolling or to include buttons among the children.
